image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - main  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  - java -jar ./artifacts/app-card-delivery.jar &

build_script:
  - chmod +x gradlew
  - gradlew test -Dselenide.headless=true  # запускаем тест, флаг --info позволяет выводить больше информации